### ISSUE TITLE
Season 1 - Discussion

### ISSUE THREAD

**Issue by GraphicDThanh** [GraphicDThanh/learn-algorithms-together#2]
Weekly Problem: Season 1 - Week 1

Easy: [35. Search Insert Position](https://leetcode.com/problems/search-insert-position/) (required)

**Comment by GraphicDThanh** [comment]
Bài này ở dạng binary search, đọc blog này để xem dạng bài này nhé =)) 
https://beautyoncode.com/tim-kiem-nhi-phanbinary-search/

**Comment by GraphicDThanh** [comment]
[Introduction to Big O Notation and Time Complexity (Data Structures & Algorithms #7)](https://www.youtube.com/watch?v=D6xkbGLQesk)

**Comment by GraphicDThanh** [comment]
Learn Binary Search https://leetcode.com/explore/learn/card/binary-search/

**Comment by GraphicDThanh** [comment]
Week 3

- Easy: [121. Best Time to Buy and Sell Stock](https://leetcode.com/problems/best-time-to-buy-and-sell-stock/) (required)
- Medium: [300. Longest Increasing Subsequence](https://leetcode.com/problems/longest-increasing-subsequence/)

**Comment by myle-agilityio** [comment]
Week 4
- Easy: [21. Merge Two Sorted Lists](https://leetcode.com/problems/merge-two-sorted-lists/)
- Medium: [7. Reverse Integer](https://leetcode.com/problems/reverse-integer/)

**Comment by ThuanDang97** [comment]
Weekly Problem: Season 1 - Week 6

Easy: [1859. Sorting the Sentence](https://leetcode.com/problems/sorting-the-sentence/) (required)
Medium: [958. Check Completeness of a Binary Tree](https://leetcode.com/problems/check-completeness-of-a-binary-tree/)(optional)

**Comment by nvmt2** [comment]
Weekly Problem: Season 1 - Week 7

Easy: [1716. Calculate Money in Leetcode Bank](https://leetcode.com/problems/calculate-money-in-leetcode-bank/) (required)
Medium: [752. Open the Lock](https://leetcode.com/problems/open-the-lock/) (optional)

**Comment by phuongbuimai-agilityio** [comment]
Weekly Problem: Season 1 - Week 8

Easy: [119. Pascal's Triangle II](https://leetcode.com/problems/pascals-triangle-ii/) (required)
Medium: [1424. Diagonal Traverse II](https://leetcode.com/problems/diagonal-traverse-ii/) (optional)

**Comment by phuongbuimai-agilityio** [comment]
Weekly Problem: Season 1 - Week 9

Easy: [541. Reverse String II](https://leetcode.com/problems/reverse-string-ii/) (required)
Medium: [77. Combinations](https://leetcode.com/problems/combinations/) (optional)
